version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: bradenmars/warriorbeat-wordpress:latest
    volumes:
      - ./src/warriorbeat:/var/www/html/wp-content/plugins/warriorbeat
      - ./docker-bootstrap.sh:/usr/local/bin/apache2-custom.sh
    ports:
      - '3000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
